package entities;
// Generated Aug 24, 2018 8:59:37 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments implements java.io.Serializable {

    private short departmentId;
    private Locations locations;
    private Employees employees;
    private String departmentName;
    private Set employeeses = new HashSet(0);

    public Departments() {
    }

    public Departments(short departmentId, String departmentName) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
    }

    public Departments(short departmentId, String departmentName, Employees employees, Locations locations) {
        this.departmentId = departmentId;
        this.locations = locations;
        this.employees = employees;
        this.departmentName = departmentName;
    }

    
    
    public Departments(short departmentId, Locations locations, Employees employees, String departmentName, Set employeeses) {
        this.departmentId = departmentId;
        this.locations = locations;
        this.employees = employees;
        this.departmentName = departmentName;
        this.employeeses = employeeses;
    }

    public short getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(short departmentId) {
        this.departmentId = departmentId;
    }

    public Locations getLocations() {
        return this.locations;
    }

    public void setLocations(Locations locations) {
        this.locations = locations;
    }

    public Employees getEmployees() {
        return this.employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }

}
