package entities;
// Generated Aug 24, 2018 8:59:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private String jobId;
     private String jobTitle;
     private Integer minSalary;
     private Integer maxSalary;
     private Set employeeses = new HashSet(0);

    public Jobs() {
    }
	
    public Jobs(String jobId, String jobTitle) {
        this.jobId = jobId;
        this.jobTitle = jobTitle;
    }

    public Jobs(String jobId, String jobTitle, Integer minSalary, Integer maxSalary) {
        this.jobId = jobId;
        this.jobTitle = jobTitle;
        this.minSalary = minSalary;
        this.maxSalary = maxSalary;
    }
    
    public Jobs(String jobId, String jobTitle, Integer minSalary, Integer maxSalary, Set employeeses) {
       this.jobId = jobId;
       this.jobTitle = jobTitle;
       this.minSalary = minSalary;
       this.maxSalary = maxSalary;
       this.employeeses = employeeses;
    }
   
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Integer getMinSalary() {
        return this.minSalary;
    }
    
    public void setMinSalary(Integer minSalary) {
        this.minSalary = minSalary;
    }
    public Integer getMaxSalary() {
        return this.maxSalary;
    }
    
    public void setMaxSalary(Integer maxSalary) {
        this.maxSalary = maxSalary;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


